// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"7aeocvihdd","name":"Pets","description":"","endpoint":"https://7aeocvihdd.execute-api.us-west-2.amazonaws.com/Development","region":"us-west-2","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:344f0d89-5912-4edc-b64d-e7d257387ef0',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'myproject-hosting-mobilehub-1291603333',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dczheqtflnpwp.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"myproject-mobilehub-1291603333-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-west-2","hashKey":"userId","rangeKey":"petId"}],
    'aws_mobile_analytics_app_id': '51d68587cf4143d2a1f875b744d6e9e8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ac5fd117-06b1-46cc-8a6d-75567b500b1c',
    'aws_project_name': 'my-project-2018-05-08-16-23-01',
    'aws_project_region': 'us-west-2',
    'aws_resource_bucket_name': 'myproject-deployments-mobilehub-1291603333',
    'aws_resource_name_prefix': 'myproject-mobilehub-1291603333',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'myproject-userfiles-mobilehub-1291603333',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_cqAyzrR36',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': 'qvqu0d3cjer8hkfldqvjg6jld',
}

export default awsmobile;
